image: gitlab/dind

stages:
  - build

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - docker build -t registry.gitlab.com/emvn/emvn-ico:$CI_COMMIT_REF_NAME .
    - docker push registry.gitlab.com/emvn/emvn-ico:$CI_COMMIT_REF_NAME
